export enum SkillMechanics {
    POWER_GAGE = "POWER_GAGE",
    TIME_GATED = "TIME_GATED",
    DOUBLE_TEAM = "DOUBLE_TEAM", //TODO HAND
    STATUS_EFFECT = "STATUS_EFFECT",
    SELF_STATUS_EFFECT = "SELF_STATUS_EFFECT",
    STATE = "STATE",
    CREATE_SHIELD = "CREATE_SHIELD",
    COUNTER = "COUNTER",
    CHARGE = "CHARGE",
    MOVABLE_SKILL = "MOVABLE_SKILL",
    IGONORES_OBSTACLE = "IGONORES_OBSTACLE",
}

export type SkillMechanicsType = keyof typeof SkillMechanics;


export enum CharacterMechanics {
    TRANSFORM = "TRANSFORM",
    ELEMENT_CHANGE = "ELEMENT_CHANGE",
    CLASS_CHANGE = "CLASS_CHANGE",
    CHARACTER_SWAP = "CHARACTER_SWAP",
    STATUS_EFFECT = "STATUS_EFFECT",
    SELF_STATUS_EFFECT = "SELF_STATUS_EFFECT",
    POWER_GAGE = "POWER_GAGE",
    TREASURE_AREA_EFFECT = "TREASURE_AREA_EFFECT",
    STATE = "STATE",
    SKILL_TRANSFORM = "SKILL_TRANSFORM",
    DEFENSIVE_SHIELD = "DEFENSIVE_SHIELD",
    CREATE_SHIELD = "CREATE_SHIELD",
    IGONORES_OBSTACLE = "IGONORES_OBSTACLE",
    DOUBLE_TEAM = "DOUBLE_TEAM", //TODO HAND
    IGNORE_ENEMY_CAPTURE = "IGNORE_ENEMY_CAPTURE",
    IGNORE_ENEMY_REFILL = "IGNORE_ENEMY_REFILL",
    COUNTER = "COUNTER",
    CHARGE = "CHARGE",
    IMMEDIATE_KO = "IMMEDIATE_KO",
    MOVABLE_SKILL = "MOVABLE_SKILL",
    ONE_HP_WILL_BE_LEFT = "ONE_HP_WILL_BE_LEFT",
    NULLIFY_ONE_HP_WILL_BE_LEFT = "NULLIFY_ONE_HP_WILL_BE_LEFT",
    RECOVER_HP_WHEN_KOED = "RECOVER_HP_WHEN_KOED",
    NULIFY_RECOVER_HP_WHEN_KOED = "NULIFY_RECOVER_HP_WHEN_KOED",
}

export type CharacterMechanicsType = keyof typeof CharacterMechanics;