export enum MedalTrait {
    // Limits / Stats
    DAMAGE_INCREASE = "DAMAGE_INCREASE",
    DAMAGE_REDUCTION = "DAMAGE_REDUCTION",
    BOOST_CD_SKILL_1 = "BOOST_CD_SKILL_1",
    BOOST_CD_SKILL_2 = "BOOST_CD_SKILL_2",
    BOOST_CD_DODGE = "BOOST_CD_DODGE",
    CAPTURE_SPEED = "CAPTURE_SPEED",
    HP_PERCENTAGE = "HP_PERCENTAGE",
    ATK_PERCENTAGE = "ATK_PERCENTAGE",
    DEF_PERCENTAGE = "DEF_PERCENTAGE",
    CRIT_PERCENTAGE = "CRIT_PERCENTAGE",
    SPD_PERCENTAGE = "SPD_PERCENTAGE",
    HP_POINTS = "HP_POINTS",
    ATK_POINTS = "ATK_POINTS",
    DEF_POINTS = "DEF_POINTS",
    CRIT_POINTS = "CRIT_POINTS",
    STATUS_EFFECT_REDUCTION = "STATUS_EFFECT_REDUCTION",
    NORMAL_ATK_DAMAGE = "NORMAL_ATK_DAMAGE",

    // Applies immediately, timed boosts, or status effects
    HP_RECOVERY = "HP_RECOVERY",
    INCREASE_TREASURE_GAUGE_RECOVERY = "INCREASE_TREASURE_GAUGE_RECOVERY",
    INCREASE_TREASURE_GAUGE_AMMOUNT_WHEN_CAPTURE = "INCREASE_TREASURE_GAUGE_AMMOUNT_WHEN_CAPTURE",
    BOOST_CRIT = "BOOST_CRIT",
    NULLIFY_STUN = "NULLIFY_STUN",
    NULLIFY_SHOCK = "NULLIFY_SHOCK",
    NULLIFY_TREMOR = "NULLIFY_TREMOR",
    NULLIFY_FREEZE = "NULLIFY_FREEZE",
    NULLIFY_AFLAME = "NULLIFY_AFLAME",
    INFLICT_POISON = "INFLICT_POISON",
    INFLICT_SHOCK = "INFLICT_SHOCK",
    BOOST_SPEED = "BOOST_SPEED",
    REDUCE_CD_SKILL_1 = "REDUCE_CD_SKILL_1",
    REDUCE_CD_SKILL_2 = "REDUCE_CD_SKILL_2",
}

export type MedalTraitType = keyof typeof MedalTrait;