export enum MedalTrait {
    // Limits / Stats

    // --- DAMAGE / REDUCTION ---
    DMG_INCREASE = "DMG_INCREASE",
    DMG_REDUCTION = "DMG_REDUCTION",
    NORMAL_ATK_DAMAGE = "NORMAL_ATK_DAMAGE",

    // --- COOLDOWN SPEED REDUCTION  ---
    SKILL_1_CD_SPEED = "SKILL_1_CD_SPEED",
    SKILL_2_CD_SPEED = "SKILL_2_CD_SPEED",
    DODGE_CD_SPEED = "DODGE_CD_SPEED",


    // --- FLAT REDUCTION (IMMEDIATE) ---
    SKILL_1_CD_REDUCTION = "SKILL_1_CD_REDUCTION",
    SKILL_2_CD_REDUCTION = "SKILL_2_CD_REDUCTION",

    // --- STATS PERCENTAGE ---
    HP_PERCENTAGE = "HP_PERCENTAGE",
    ATK_PERCENTAGE = "ATK_PERCENTAGE",
    DEF_PERCENTAGE = "DEF_PERCENTAGE",
    CRIT_PERCENTAGE = "CRIT_PERCENTAGE",
    SPD_PERCENTAGE = "SPD_PERCENTAGE",

    // --- STATS FLAT ---
    HP_FLAT = "HP_FLAT",
    ATK_FLAT = "ATK_FLAT",
    DEF_FLAT = "DEF_FLAT",
    CRIT_FLAT = "CRIT_FLAT",

    // --- RECOVERY / CAPTURE ---
    CAPTURE_SPEED = "CAPTURE_SPEED",
    HP_RECOVERY = "HP_RECOVERY", // (IMMEDIATE)
    TREASURE_GAUGE_RECOVERY = "TREASURE_GAUGE_RECOVERY",
    TREASURE_GAUGE_CAPTURE = "TREASURE_GAUGE_CAPTURE",

    // --- BOOSTS (TIMED) ---
    BUFF_CRIT_TIMED = "BUFF_CRIT_TIMED",
    BUFF_SPD_TIMED = "BUFF_SPD_TIMED",

    // --- STATUS EFFECT ---
    STATUS_REDUCTION = "STATUS_REDUCTION",
    STATUS_NULLIFY_CHANCE = "STATUS_NULLIFY_CHANCE",
    STATUS_INFLICT_CHANCE = "STATUS_INFLICT_CHANCE",
}

export type MedalTraitType = keyof typeof MedalTrait;

export enum MedalTraitConstraint {
    // --- COMBATS/KO ---
    ON_KO_SELF = "ON_KO_SELF",
    ON_RESPAWN = "ON_RESPAWN",
    ON_KO_TEAM = "ON_KO_TEAM",
    ON_ALLY_DEAD = "ON_ALLY_DEAD",
    ON_KB_DEALT = "ON_KB_DEALT",
    ON_KB_TAKEN = "ON_KB_TAKEN",
    ON_DOWN_DEALT = "ON_DOWN_DEALT",
    ON_DOWN_TAKEN = "ON_DOWN_TAKEN",

    // --- HP AND TIME ---
    HP_LT = "HP_LT",
    HP_GT = "HP_GT",
    TIME_LT = "TIME_LT",
    TIME_GT = "TIME_GT",
    ON_MATCH_START_TIMED = "ON_MATCH_START_TIMED",

    // --- TREASURES ---
    AREA_ENEMY = "AREA_ENEMY",
    AREA_TEAM = "AREA_TEAM",
    AREA_ANY = "AREA_ANY",
    TREASURE_LESS = "TREASURE_LESS",
    TREASURE_MORE = "TREASURE_MORE",
    ON_CAP_SELF = "ON_CAP_SELF",
    ON_CAP_TEAM = "ON_CAP_TEAM",
    ALLY_NEAR = "ALLY_NEAR",
    ALLY_AWAY = "ALLY_AWAY",
    GAUGE_SET = "GAUGE_SET",
    GAUGE_GT = "GAUGE_GT",
    GAUGE_LT = "GAUGE_LT",
    ON_FLAG_LOST = "ON_FLAG_LOST",

    // --- SKILLS AND STATUS ---
    ON_S2_USE = "ON_S2_USE",
    ON_S2_HIT = "ON_S2_HIT",
    ON_S1_USE = "ON_S1_USE",
    ON_STATUS_NULL = "ON_STATUS_NULL",
    ON_STATUS_GET = "ON_STATUS_GET",
    ON_STATUS_SET = "ON_STATUS_SET",
    ON_ATTACK_STATUS = "ON_ATTACK_STATUS",
    ON_ATTACKED_STATUS = "ON_ATTACKED_STATUS",

    // --- OTHER INTERACTIONS ---
    ON_NORMALS = "ON_NORMALS",
    ON_ATTACK_TAG = "ON_ATTACK_TAG",
    ON_ATTACKED_TAG = "ON_ATTACKED_TAG",
    ON_ATTACK_CAP = "ON_ATTACK_CAP",
    ON_ENEMY_CAP = "ON_ENEMY_CAP",
    ON_CRIT = "ON_CRIT",
    ON_PDODGE = "ON_PDODGE",
    ON_ATTACK = "ON_ATTACK",
    ON_ATTACKED = "ON_ATTACKED",
    ON_BIG_HIT = "ON_BIG_HIT",
    ON_ATTACK_ELEM_SAME = "ON_ATTACK_ELEM_SAME",
    ON_ATTACK_ELEM_WEAKER = "ON_ATTACK_ELEM_WEAKER",
    ON_ATTACK_BUFF_DEF = "ON_ATTACK_BUFF_DEF",
    ON_ATTACK_BUFF_ATK = "ON_ATTACK_BUFF_ATK",
    ON_ATTACKED_BUFF_ATK = "ON_ATTACKED_BUFF_ATK",
    SELF_TAG = "SELF_TAG",
}

export type MedalTraitConstraintType = keyof typeof MedalTraitConstraint;

