export enum StatusEffect {
    CAPTURE_BLOCK = "CAPTURE_BLOCK",
    CLAWED = "CLAWED",
    SINGSING = "SINGSING",
    GOLD = "GOLD",
    SEWSEW = "SEWSEW",
    CALM = "CALM",
    NEGATIVE = "NEGATIVE",
    STOLEN_HEART = "STOLEN_HEART",
    RECOVERY_BLOCK = "RECOVERY_BLOCK",
    SLEEP = "SLEEP",
    BIND = "BIND",
    TOY = "TOY",
    FROSTBITE = "FROSTBITE",
    FILM = "FILM",
    CANDYMAN = "CANDYMAN",
    SEALED = "SEALED",
    CUTOUT = "CUTOUT",
    SPIDERWEB = "SPIDERWEB",
    HORMONE = "HORMONE",
    VENOM = "VENOM",
    POISON = "POISON",
    TREMOR = "TREMOR",
    ICE_BALL = "ICE_BALL",
    GRAVITY = "GRAVITY",
    CONFUSE = "CONFUSE",
    FREEZE = "FREEZE",
    STUN = "STUN",
    AFLAME = "AFLAME",
    DARK = "DARK",
    SHOCK = "SHOCK",
    MAX_HP_REDUCTION = "MAX_HP_REDUCTION",
    ENTRANCE = "ENTRANCE"
}

export type StatusEffectType = keyof typeof StatusEffect;